config/routes.rb
Rails.application.routes.draw do


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "home#index"

 
  resources :users
  resources :rooms do
    resources :reviews
    resources :bookings
  end
  get 'about/index'
  get 'gallery/index'
  
  resources :user_sessions, only: [ :new, :create, :destroy ]
  get 'login'  => 'user_sessions#new'
  get 'logout' => 'user_sessions#destroy'


end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[ show edit update destroy ]
  before_action :require_login
  # GET /bookings or /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1 or /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @room_options = Room.all.map{ |r| [ r.room_no, r.id ] }
    @booking = Booking.new
    @room = Room.find(params[:room_id])
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings or /bookings.json
  def create
    @room = Room.find(params[:room_id])
    @user = User.find(current_user.id)
    @booking = @room.bookings.new(booking_params)
    @booking.user = @user

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @room, notice: "Booking was successfully created." }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1 or /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: "Booking was successfully updated." }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1 or /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: "Booking was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def booking_params
      params.require(:booking).permit(:name, :days, :occupants, :food, :room_id, :user_id)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= form_for [ @room, @booking ] do |form| %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name , :required => true %>
  </div>

  <div class="field">
    <%= form.label :days %>
    <%= form.number_field :days , :required => true %>
  </div>

  <div class="field">
    <%= form.label :occupants %>
    <%= form.number_field :occupants, :required => true  %>
  </div>

  <div class="field">
    <%= form.label :food %>
    <%= form.check_box :food %>
  </div>

  <div class="field">
    <%= form.label :room_id %>
    <%= form.select(:room_id, @room_options) %>
  </div>
  

  <div class="actions">
    <%= form.submit "Book", class: "button is-light" %>
    <%= link_to "Back", room_path(@room.id), class: "button is-light" %>
  </div>
  <hr>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bookings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User Name</th>
      <th>Days</th>
      <th>Occupants</th>
      <th>Food</th>
      <th>Room</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.name %></td>
        <td><%= booking.user_name %></td>
        <td><%= booking.days %></td>
        <td><%= booking.occupants %></td>
        <td><%= booking.food %></td>
        <td><%= booking.room_id %></td>
        <td><%= link_to 'Show', booking %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', new_room_booking_path %>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form', booking: @room_booking %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Days:</strong>
  <%= @booking.days %>
</p>

<p>
  <strong>Occupants:</strong>
  <%= @booking.occupants %>
</p>

<p>
  <strong>Food:</strong>
  <%= @booking.food %>
</p>

<p>
  <strong>Room:</strong>
  <%= @booking.room_id %>
</p>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>