config/routes.rb
Rails.application.routes.draw do


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "home#index"

 
  resources :users
  resources :rooms do
    resources :reviews
    resources :bookings
  end
  get 'about/index'
  get 'gallery/index'
  
  resources :user_sessions, only: [ :new, :create, :destroy ]
  get 'login'  => 'user_sessions#new'
  get 'logout' => 'user_sessions#destroy'


end

app/models/room.rb
class Room < ApplicationRecord
    has_many :reviews , dependent: :destroy
    has_many :bookings
    has_attached_file :image
    accepts_nested_attributes_for :bookings
    validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :require_login, except: [:index, :show]

  def index
    @rooms = Room.all
  end

  def show
    @room = Room.find(params[:id])

    @review = Review.new
    @review.room_id = @room.id

  end

  def new
    @room = Room.new
    @booking = Booking.new
  end

  def create
    @room = Room.new(room_params)
    @room.save
    flash.notice = "Room '#{@room.room_no}' created!"
    redirect_to rooms_path
  end
  
  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    flash.notice = "Room '#{@room.room_no}' destroyed!"

    redirect_to rooms_path
  end

  def edit
    @room = Room.find(params[:id])
  end

  def update
    @room = Room.find(params[:id])
    @room.update(room_params)
    flash.notice = "Room '#{@room.room_no}' Updated!"

    redirect_to rooms_path
  
  end

  private
    def room_params
        params.require(:room).permit(:room_no, :description, :price, :image)
    end

end

app/helpers/rooms_helper.rb
module RoomsHelper

end

app/views/rooms/_form.html.erb
<%= form_for(@room, html: {multipart: true}) do |f| %>
  <ul>
  <% @room.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :room_number %><br />
    <%= f.text_field :room_no %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :price %><br />
    <%= f.text_area :price %>
  </p>
  <p>
      <% if @room.image.exists? %>
        <%= image_tag @room.image_file_name, size: '300x300'%><br/>
      <% end %>

      <%= f.label :image, "Attach a New Image" %><br />
      <%= f.file_field :image %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to "<< Back to all rooms", rooms_path %>

app/views/rooms/_review.html.erb
<div>
  <h3>Reviewed by <%= review.user_name %></h3>
  <p class="comment"><%= review.body %></p>
  <p class="has-text-black">Posted <%= distance_of_time_in_words(review.created_at, Time.now) %> ago</p>
  <% if logged_in? and current_user.admin? %>
    <%= link_to "Delete", room_review_path(@room, review),class: "has-text-danger", method: :delete, data: {confirm: "Do you really wanna delete the comment?" } %>
  <% end %>

</div>
<hr>

app/views/rooms/edit.html.erb
<h1>Edit room: <%= @room.room_no%></h1>

<%= render partial: 'form' %>

app/views/rooms/index.html.erb
<h1>Rooms available:</h1>

<div class='container'>

    <% @rooms.each do |room| %>
        <p class="has-text-centered "><%= link_to "Room: #{room.room_no} ", room_path(room) %></p>
        <br />
        <div class="is-flex is-justify-content-center">
        <% if room.image.exists? %>  
          <%= link_to (image_tag(room.image_file_name, size: '200x200')), room_path(room) %>
        <% end %>
        </div>

        <div class="has-text-centered">
          <% if logged_in? and current_user.admin? %>
            <%= link_to "Edit", edit_room_path(room), class: "has-text-success" %>
            <%= link_to "Delete", room_path(room) ,class: "has-text-danger", method: :delete, data: {confirm: "Do you really wanna delete the room?"} %>
          <% end %>
        </div>

    <% end %>
<div>

  <% if logged_in? and current_user.admin? %>
    <%= link_to "Create new room", "rooms/new" , class: "has-text-success"%>
  <% end %>  

app/views/rooms/new.html.erb
<h1>Create a new room</h1>

<%= render partial: 'form' %>

app/views/rooms/show.html.erb
<p class='content'>
    <% if @room.image.exists? %>
        <%= image_tag @room.image_file_name, size: '500x500' %>
    <% end %>
    <h1>Room:</h1> <%= @room.room_no %>
    <h1>About the room:</h1> <%= @room.description %>
    <h1>Price:</h1>  <%= @room.price %>

</p>

<div class="button is-primary">
    <%= link_to "Book now!", new_room_booking_path(@room.id) %>
</div>
<hr>

<h2>Reviews (<%= @room.reviews.size%>):</h2>
<hr>
<%= render partial: 'rooms/review', collection: @room.reviews %>
<% if logged_in? %>
    <%= render partial: 'reviews/form' %>
<% end %>
<%= link_to "<< Back to all rooms", rooms_path %>