config/routes.rb
Rails.application.routes.draw do


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "home#index"

 
  resources :users
  resources :rooms do
    resources :reviews
    resources :bookings
  end
  get 'about/index'
  get 'gallery/index'
  
  resources :user_sessions, only: [ :new, :create, :destroy ]
  get 'login'  => 'user_sessions#new'
  get 'logout' => 'user_sessions#destroy'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :reviews , dependent: :destroy
    has_many :bookings
    has_attached_file :image
    accepts_nested_attributes_for :bookings
    validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  has_many :bookings
  validates_confirmation_of :password, message: "should match password", if: :password
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
    def index
        @images = Dir.glob("app/assets/images/gallery/*.jpg")
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def show
  end
  
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :require_login
  
    def create
        @room = Room.find(params[:room_id])

        @review = @room.reviews.new(review_params)
        @review.user_name = current_user.user_name
        respond_to do |format|
            if @review.save
              format.html { redirect_to room_path(@room), notice: "Review was successfully posted." }
              format.json { render :show, status: :created, location: @review }
            else
              format.html { render :new, status: :unprocessable_entity }
              format.json { render json: @review.errors, status: :unprocessable_entity }
            end
          end
    end



    def destroy
        @room = Room.find(params[:room_id])
        @review = @room.reviews.find(params[:id])
        @review.destroy
        flash.notice = "Review deleted!"
    
        redirect_to room_path(@review.room_id)
    end
    

    private
        def review_params
            params.require(:review).permit(:user_name, :body)
        end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :require_login, except: [:index, :show]

  def index
    @rooms = Room.all
  end

  def show
    @room = Room.find(params[:id])

    @review = Review.new
    @review.room_id = @room.id

  end

  def new
    @room = Room.new
    @booking = Booking.new
  end

  def create
    @room = Room.new(room_params)
    @room.save
    flash.notice = "Room '#{@room.room_no}' created!"
    redirect_to rooms_path
  end
  
  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    flash.notice = "Room '#{@room.room_no}' destroyed!"

    redirect_to rooms_path
  end

  def edit
    @room = Room.find(params[:id])
  end

  def update
    @room = Room.find(params[:id])
    @room.update(room_params)
    flash.notice = "Room '#{@room.room_no}' Updated!"

    redirect_to rooms_path
  
  end

  private
    def room_params
        params.require(:room).permit(:room_no, :description, :price, :image)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  before_action :zero_users_or_authenticated, except: [:index, :show, :new, :create]
  before_action :require_login, except: [:new, :create]
  
  def zero_users_or_authenticated
    unless User.count == 0 || current_user
      redirect_to root_path
      return false
    end
  end
  

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to root_path, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:user_name, :email, :password, :password_confirmation, :city, :state, :phone_no, :admin)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper

end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="footer has-text-black has-background-light has-text-centered">
    <p>Copyright PearBlossom 2021</p>
</div>

app/views/layouts/_navbar.html.erb
    <nav class="navbar is-dark has-text-primary-dark">
      <div class="navbar-brand">
          <%= link_to (image_tag("logo.png", alt: "Pear Blossom", size: "64x64")), root_path %>

      </div>

      <div class="navbar-menu">
        <div class="navbar-start">
          <%= link_to "Home", root_path, class: "navbar-item" %>
          <%= link_to "Rooms", rooms_path, class: "navbar-item" %>
          <%= link_to "Gallery", gallery_index_path, class: "navbar-item" %>

          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              More
            </a>

            <div class="navbar-dropdown">
              <%= link_to "About", about_index_path, class: "navbar-item" %>
              <%#= link_to "Contact", "contact/index", class: "navbar-item" %>
            </div>
          </div>
        </div>

        <div class="navbar-end">
          <div class="navbar-item">
            <div class="buttons">
              <% unless logged_in? %>
                <div class="button is-primary">
                  <%= link_to "<strong>Sign up</strong>".html_safe, "users/new" %>
                </div>
              <% end %>
              
                <% if logged_in? %>
                  <% if user.admin? %>
                    <div class="button is-primary">
                      <%= link_to "<strong>Admin Panel</strong>".html_safe, "/admin" %>
                    </div>
                  <% end %>  

                <div class="button is-primary">
                    <%= link_to "<strong>Logout</strong>".html_safe, logout_path %>
                </div>
                <% else %>
                <div class="button is-primary">
                  <%= link_to "<strong>Login</strong>".html_safe, login_path %>
                </div>
                <% end %>
              
            </div>
          </div>
        </div>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pear Blossom</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="has-background-grey-dark">
  <%= render "layouts/navbar", :user => current_user %>

    <div class="container has-background-grey-dark has-text-primary-dark">
    
      <p class="flash">
        <%= flash.notice %>
      </p>

      <%= yield %>

    </div>
  
  <%= render "layouts/footer" %>

  </body>
</html>